- Android/Make you own android app.md
> Fixed typos

- Programming Foundations/Make A Web Page.md
added <body> and stylesheet link to the tags that Codepen generates automatically, causing duplicates in students' submission
> update Make a Web Page.md

- Front End/Build a Portfolio Site.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/project-descriptions-for-review/9)
> Link to the better version of the Style Guide

- README.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/project-descriptions-for-review/10)
> Add missing words for grammar purposes

- Data-Analyst/Analyzing the New York Subway Dataset.md
Updated the instructions to remove reviewer-facing document on this repo which is easily accessible to all. Reviewer-facing document is now on the reviews app.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/project-descriptions-for-review/11)
> Update Analyzing the New York Subway Dataset.md

- Data-Analyst/Data Wrangle OpenstreetMaps Data.md
Removed link to reviewer-facing doc from this publically-accessible repo.
> Remove reviewer-facing doc link.

- Data-Analyst/Identifying Fraud from Enron Email.md
Remove reviewer-facing information from this publically-accessible repo.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/project-descriptions-for-review/14)
> Update: remove reviewer instructions

- Intro to Java.md
Added two items: win % thing, and tips regarding use of loops.  Also rearranged them so the tips are in rubric order.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/project-descriptions-for-review/16)
> Update Intro to Java.md

- Tech Entrepreneur/Interactive_Prototyping.md
- Tech Entrepreneur/Marketing_and_Distribution.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/project-descriptions-for-review/17)
> Updated Prototype and Marketing

- Full Stack/ConferenceOrganizationApp.md
- Full Stack/Linux Server Configuration.md
- Full Stack/TournamentResults.md
- Resumes, LinkedIn and GitHub Profiles.md
-Changed "linked in" to "LinkedIn" (Resumes, LinkedIn and GitHub
Profiles.md)
-Changed "quereies" to "queries" (ConferenceOrganizationApp.md)
-Added missing pronoun, "You" (ConferenceOrganizationApp.md)
-Changed capitalization in headers to be more consistent (Linux Server
Configuration.md)
-'time zone' is two words (Linux Server Configuration.md)
-Removed repeated "the" in "Refer to the the..." (TournamentResults.md)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/project-descriptions-for-review/22)
> docs: Fix grammar

- Front End/About Me.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/project-descriptions-for-review/20)
> Modify class to match starter code

- Front End/Interactive Resume Project.md
mostly just practicing my git flow!
> spelling issue

- Front End/Classic Arcade Game Clone.md
Removed the duplicated text for the "Evaluated and Submitted" section and the "What's Next" section. The duplication for the "Evaluated and Submitted" section actually used the rubric for a different project.
> Removed duplicated text

- Beginner Android/Your First App.md
> Created prelim rubric for Beginner Android

- Senior Web Dev/Meet-Up Event Planner.md
to reflect the one in the classroom
> Updating rubric

- Full Stack/TournamentResults.md
TournamentResults.md update to comment on new test suite for the tournament results project.
> Update TournamentResults.md with new test suite info

- Programming Foundations/Reverse_engineer.md
Maybe not all Reviewers have access to the IPND path (https://plus.google.com/101054535595811543328/posts/amqCQJaJRie), and to make things generally easier, I  added the links to the webapp and the Project Compass zip file here in the Project Description.
> Added two links

- Special Cases.md
A file aimed on collecting special cases that might be encountered while Project Reviewing, and best practices how to deal with them. This is just a tiny start of what I can contribute, please do extend! :)
> Create Special Cases.md

- README.md
how to handle submissions according to an outdated rubric; referencing the _Special Cases.md_ document.
> added to can't review

- Front End/Front End Grit.md
Updates to allow student to submit project via in-browser editor.
> Update Front End Grit.md

- Programming Foundations/Getting Started with HTML.md
I've encountered simple copy+paste of Andy's code. Reading the instructions here, a Reviewer who isn't familiar with that code might pass the submission:
> As long as the student submits some notes in HTML, the project will pass. 
Since I think this would miss the point, I've added two sentences regarding copy+paste issues.
---
I also deleted a stray word: "Criteria"
> add "plagiarism" section

- DevOps/P0/P0_Fictional_Startup.md
@morosebose Following up from PR66.
> Docs: Fixed typo

- Full Stack/Design A Game.md
Split [PR66](https://github.com/udacity/Project-Descriptions-for-Review/pull/66) into two. This is the the FSND Design a Game clarification.
> Docs: Clarified Task 2 -- Guess a Date DNMS

- BiOS/Alien Adventure 1
- BiOS/Alien Adventure 2
- BiOS/Alien Adventure 3
- BiOS/Alien Adventure 4
- BiOS/Pirate Fleet 1
- BiOS/Pirate Fleet 2
- BiOS/Robot Maze 2
- BiOS/Silly Song
> Add descriptions for BiOS Projects

- Front End/Animal Trading Cards.md
> Change file url to download

- Front End/Animal Trading Cards.md
I added a link to the Udacity Frontend Nanodegree Style Guide.
> Styleguide reminder

- Career/Technical Interview Practice (Python).md
Improve readability a bit with syntax highlighting and spacing
> Update Technical Interview Practice (Python).md
